### ISSUE TITLE
Streaming with whole doc chunker seems to hang

### ISSUE THREAD

**Issue by evaline-ju** [foundation-model-stack/fms-guardrails-orchestrator#169]
## Describe the bug

In configuring an output detector with the `whole_doc_chunker` and using the streaming endpoint, the call seems to hang.

## Sample Code

In config
```
detectors:
    detector_id:
        service:
            hostname: <host>
            port: 443
        chunker_id: whole_doc_chunker
        default_threshold: 0.0
```

```
curl -k 'POST' \
  'http://localhost:8033/api/v1/task/server-streaming-classification-with-text-generation' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "model_id": "model-id",
  "inputs": "Jason is a jerk. The chicken crossed the road. The social security number is 123-45-6789. His phone number is (408) 123-4567.",
  "guardrail_config": {
    "input": {
      "masks": [],
      "models": {}
    },
    "output": {
      "models": {"detector_id": {}}
    }
  },
  "text_gen_parameters": {
    "max_new_tokens": 50,
    "min_new_tokens": 50,
    "decoding_method": "SAMPLING",
    "seed": 12,
    "preserve_input_text": true,
    "input_tokens": true,
    "generated_tokens": true
  }
}
```

## Expected behavior

No hanging, results return eventually

## Observed behavior

Hanging call

## Additional context

Unary call with `classification-with-text-generation` seems to return expected results
