### ISSUE TITLE
NLP client not working on tokenize at least

### ISSUE THREAD

**Issue by evaline-ju** [foundation-model-stack/fms-guardrails-orchestrator#88]
## Describe the bug

When testing with the NLP client for the generation provider as opposed to the TGIS client, tokenization with the LLM unexpectedly fails. It is not clear at this time whether or not generation with the NLP client works.

## Sample Code

As config use the `nlp` provider with a caikit-nlp pod

e.g. [or localhost if port-forwarded]
```
        provider: nlp # tgis or nlp
        service:
            hostname: caikit-inference
            port: 8085
```

instead of the tgis client e.g. 
```
        provider: tgis # tgis or nlp
        service:
            hostname: model-inference-server
            port: 8033
```

## Expected behavior

Same success as with the TGIS client

## Observed behavior

404 seen on tokenization for the LLM model
